/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_hellojni6_MyParcel */

#ifndef _Included_com_example_hellojni6_MyParcel
#define _Included_com_example_hellojni6_MyParcel
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_hellojni6_MyParcel
 * Method:    nativeCreate
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL
Java_com_example_hellojni6_MyParcel_nativeCreate
        (JNIEnv *, jobject);

/*
 * Class:     com_example_hellojni6_MyParcel
 * Method:    nativeWriteInt
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_example_hellojni6_MyParcel_nativeWriteInt
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_hellojni6_MyParcel
 * Method:    nativeSetDataPosition
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL
Java_com_example_hellojni6_MyParcel_nativeSetDataPosition
        (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     com_example_hellojni6_MyParcel
 * Method:    nativeReadInt
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL
Java_com_example_hellojni6_MyParcel_nativeReadInt
        (JNIEnv *, jobject, jlong);

#ifdef __cplusplus
}
#endif
#endif
