/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <string>
/* Header for class com_example_hellojni_MainActivity */

// 定义宏 _Included_com_example_hellojni_MainActivity，用于防止重复定义宏和重复包含头文件
#ifndef _Included_com_example_hellojni_MainActivity
#define _Included_com_example_hellojni_MainActivity
// 如果是 C++ 环境
#ifdef __cplusplus
// 则采用C语言编译方式；C语言不允许函数重载，避免函数名相同带来的问题
extern "C" {
#endif // __cplusplus
#undef com_example_hellojni_MainActivity_NUM
#define com_example_hellojni_MainActivity_NUM 100L
/*
 * Class:     com_example_hellojni_MainActivity
 * Method:    getStringPwd
 * Signature: ()Ljava/lang/String;
 */
// 函数的声明
JNIEXPORT jstring JNICALL Java_com_example_hellojni_MainActivity_getStringPwd
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
// 定义了 #if 或 #ifdef/#ifndef，必须要结束if #endif
#endif // __cplusplus
#endif // _Included_com_example_hellojni_MainActivity
